# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Patrick Oppenlander <patrick.oppenlander@gmail.com>

_gemname=neatjson
pkgname=ruby-$_gemname
pkgver=0.10.5
pkgrel=1
pkgdesc='Pretty, powerful, flexible JSON generation.'
arch=(any)
url='http://github.com/Phrogz/NeatJSON'
license=(MIT)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha256sums=('1ac432ab40c5b7ede55918fc78af996494c24b51ce3c3ea0f63f1bea11a6a172')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE.txt" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.txt"
}
